name: ICE_CREAM_APP
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  image_picker: ^1.0.4
  webview_flutter: ^3.0.4
  provider: ^6.1.1
  firebase_messaging: ^14.7.5
  http: ^1.0.0
  appwrite: ^0.10.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/images/
