// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANXT5CXKwJhZ0-eEwIkD4QmFxTgK-w-Y8',
    appId: '1:923440131956:web:8249b6ce446c54a7f30621',
    messagingSenderId: '923440131956',
    projectId: 'creamy-app-872a1',
    authDomain: 'creamy-app-872a1.firebaseapp.com',
    storageBucket: 'creamy-app-872a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB78SYpUgC2pagzTS_uJJCDU6U1KWpGGxg',
    appId: '1:923440131956:android:0eb9e954b8e88669f30621',
    messagingSenderId: '923440131956',
    projectId: 'creamy-app-872a1',
    storageBucket: 'creamy-app-872a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjX8f_-mJYUM_bWoPXcxxSBLxEwrVBn5U',
    appId: '1:923440131956:ios:a87a47289dcb52a1f30621',
    messagingSenderId: '923440131956',
    projectId: 'creamy-app-872a1',
    storageBucket: 'creamy-app-872a1.appspot.com',
    iosBundleId: 'com.example.flutterApplicationShinta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjX8f_-mJYUM_bWoPXcxxSBLxEwrVBn5U',
    appId: '1:923440131956:ios:05ff12d44e1a1adff30621',
    messagingSenderId: '923440131956',
    projectId: 'creamy-app-872a1',
    storageBucket: 'creamy-app-872a1.appspot.com',
    iosBundleId: 'com.example.flutterApplicationShinta.RunnerTests',
  );
}
